version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
  
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@test.com
      - PGADMIN_DEFAULT_PASSWORD=
    ports:
      - 5050:80
    volumes:
      - pgadmin:/srv/pgadmin
volumes:
  pgdata:
  pgadmin: